### ISSUE TITLE
[PedestronColab.ipynb]The Notebook Does Not Appear to Be Valid JSON

### ISSUE THREAD

**Issue by LakeOcean** [tinyvision/SOLIDER-PedestrianDetection#2]
![image](https://github.com/tinyvision/SOLIDER-PedestrianDetection/assets/30852123/f473d0cf-d12a-47b6-ae73-bb92024289f8)
[PedestronColab.ipynb](https://github.com/tinyvision/SOLIDER-PedestrianDetection/blob/master/colab/PedestronColab.ipynb)
I can not open this file.

**Comment by cwhgn** [comment]
Thanks for your attention. Our PedestronColab.ipynb is copied from Pedestron Repo. You can refer [the new version of PedestronColab.ipynb](https://github.com/hasanirtiza/Pedestron/blob/master/colab/PedestronColab.ipynb) in Pedestron.
